/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FirewallPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallPostRequest{}

// FirewallPostRequest struct for FirewallPostRequest
type FirewallPostRequest struct {
	// Name of the firewall
	Name *string `json:"name,omitempty"`
	Rules []FirewallPostRequestRulesInner `json:"rules,omitempty"`
}

// NewFirewallPostRequest instantiates a new FirewallPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallPostRequest() *FirewallPostRequest {
	this := FirewallPostRequest{}
	return &this
}

// NewFirewallPostRequestWithDefaults instantiates a new FirewallPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallPostRequestWithDefaults() *FirewallPostRequest {
	this := FirewallPostRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FirewallPostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FirewallPostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FirewallPostRequest) SetName(v string) {
	o.Name = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *FirewallPostRequest) GetRules() []FirewallPostRequestRulesInner {
	if o == nil || IsNil(o.Rules) {
		var ret []FirewallPostRequestRulesInner
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPostRequest) GetRulesOk() ([]FirewallPostRequestRulesInner, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *FirewallPostRequest) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []FirewallPostRequestRulesInner and assigns it to the Rules field.
func (o *FirewallPostRequest) SetRules(v []FirewallPostRequestRulesInner) {
	o.Rules = v
}

func (o FirewallPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableFirewallPostRequest struct {
	value *FirewallPostRequest
	isSet bool
}

func (v NullableFirewallPostRequest) Get() *FirewallPostRequest {
	return v.value
}

func (v *NullableFirewallPostRequest) Set(val *FirewallPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallPostRequest(val *FirewallPostRequest) *NullableFirewallPostRequest {
	return &NullableFirewallPostRequest{value: val, isSet: true}
}

func (v NullableFirewallPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


