/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LoadbalancerIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoadbalancerIdPutRequest{}

// LoadbalancerIdPutRequest struct for LoadbalancerIdPutRequest
type LoadbalancerIdPutRequest struct {
	Listeners []LoadbalancerPostRequestListenersInner `json:"listeners,omitempty"`
}

// NewLoadbalancerIdPutRequest instantiates a new LoadbalancerIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadbalancerIdPutRequest() *LoadbalancerIdPutRequest {
	this := LoadbalancerIdPutRequest{}
	return &this
}

// NewLoadbalancerIdPutRequestWithDefaults instantiates a new LoadbalancerIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadbalancerIdPutRequestWithDefaults() *LoadbalancerIdPutRequest {
	this := LoadbalancerIdPutRequest{}
	return &this
}

// GetListeners returns the Listeners field value if set, zero value otherwise.
func (o *LoadbalancerIdPutRequest) GetListeners() []LoadbalancerPostRequestListenersInner {
	if o == nil || IsNil(o.Listeners) {
		var ret []LoadbalancerPostRequestListenersInner
		return ret
	}
	return o.Listeners
}

// GetListenersOk returns a tuple with the Listeners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadbalancerIdPutRequest) GetListenersOk() ([]LoadbalancerPostRequestListenersInner, bool) {
	if o == nil || IsNil(o.Listeners) {
		return nil, false
	}
	return o.Listeners, true
}

// HasListeners returns a boolean if a field has been set.
func (o *LoadbalancerIdPutRequest) HasListeners() bool {
	if o != nil && !IsNil(o.Listeners) {
		return true
	}

	return false
}

// SetListeners gets a reference to the given []LoadbalancerPostRequestListenersInner and assigns it to the Listeners field.
func (o *LoadbalancerIdPutRequest) SetListeners(v []LoadbalancerPostRequestListenersInner) {
	o.Listeners = v
}

func (o LoadbalancerIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoadbalancerIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Listeners) {
		toSerialize["listeners"] = o.Listeners
	}
	return toSerialize, nil
}

type NullableLoadbalancerIdPutRequest struct {
	value *LoadbalancerIdPutRequest
	isSet bool
}

func (v NullableLoadbalancerIdPutRequest) Get() *LoadbalancerIdPutRequest {
	return v.value
}

func (v *NullableLoadbalancerIdPutRequest) Set(val *LoadbalancerIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadbalancerIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadbalancerIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadbalancerIdPutRequest(val *LoadbalancerIdPutRequest) *NullableLoadbalancerIdPutRequest {
	return &NullableLoadbalancerIdPutRequest{value: val, isSet: true}
}

func (v NullableLoadbalancerIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadbalancerIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


