/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FirewallPostRequestRulesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallPostRequestRulesInner{}

// FirewallPostRequestRulesInner struct for FirewallPostRequestRulesInner
type FirewallPostRequestRulesInner struct {
	Protocol *string `json:"protocol,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Src *string `json:"src,omitempty"`
}

// NewFirewallPostRequestRulesInner instantiates a new FirewallPostRequestRulesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallPostRequestRulesInner() *FirewallPostRequestRulesInner {
	this := FirewallPostRequestRulesInner{}
	return &this
}

// NewFirewallPostRequestRulesInnerWithDefaults instantiates a new FirewallPostRequestRulesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallPostRequestRulesInnerWithDefaults() *FirewallPostRequestRulesInner {
	this := FirewallPostRequestRulesInner{}
	return &this
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *FirewallPostRequestRulesInner) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPostRequestRulesInner) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *FirewallPostRequestRulesInner) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *FirewallPostRequestRulesInner) SetProtocol(v string) {
	o.Protocol = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *FirewallPostRequestRulesInner) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPostRequestRulesInner) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *FirewallPostRequestRulesInner) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *FirewallPostRequestRulesInner) SetPort(v int32) {
	o.Port = &v
}

// GetSrc returns the Src field value if set, zero value otherwise.
func (o *FirewallPostRequestRulesInner) GetSrc() string {
	if o == nil || IsNil(o.Src) {
		var ret string
		return ret
	}
	return *o.Src
}

// GetSrcOk returns a tuple with the Src field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPostRequestRulesInner) GetSrcOk() (*string, bool) {
	if o == nil || IsNil(o.Src) {
		return nil, false
	}
	return o.Src, true
}

// HasSrc returns a boolean if a field has been set.
func (o *FirewallPostRequestRulesInner) HasSrc() bool {
	if o != nil && !IsNil(o.Src) {
		return true
	}

	return false
}

// SetSrc gets a reference to the given string and assigns it to the Src field.
func (o *FirewallPostRequestRulesInner) SetSrc(v string) {
	o.Src = &v
}

func (o FirewallPostRequestRulesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallPostRequestRulesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Src) {
		toSerialize["src"] = o.Src
	}
	return toSerialize, nil
}

type NullableFirewallPostRequestRulesInner struct {
	value *FirewallPostRequestRulesInner
	isSet bool
}

func (v NullableFirewallPostRequestRulesInner) Get() *FirewallPostRequestRulesInner {
	return v.value
}

func (v *NullableFirewallPostRequestRulesInner) Set(val *FirewallPostRequestRulesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallPostRequestRulesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallPostRequestRulesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallPostRequestRulesInner(val *FirewallPostRequestRulesInner) *NullableFirewallPostRequestRulesInner {
	return &NullableFirewallPostRequestRulesInner{value: val, isSet: true}
}

func (v NullableFirewallPostRequestRulesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallPostRequestRulesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


