/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VpcIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcIdPutRequest{}

// VpcIdPutRequest struct for VpcIdPutRequest
type VpcIdPutRequest struct {
	// Public IPv4 address of the member
	Ip4public string `json:"ip4public"`
	// Private IPv4 address of the member
	Ip4private *string `json:"ip4private,omitempty"`
}

type _VpcIdPutRequest VpcIdPutRequest

// NewVpcIdPutRequest instantiates a new VpcIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcIdPutRequest(ip4public string) *VpcIdPutRequest {
	this := VpcIdPutRequest{}
	this.Ip4public = ip4public
	return &this
}

// NewVpcIdPutRequestWithDefaults instantiates a new VpcIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcIdPutRequestWithDefaults() *VpcIdPutRequest {
	this := VpcIdPutRequest{}
	return &this
}

// GetIp4public returns the Ip4public field value
func (o *VpcIdPutRequest) GetIp4public() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip4public
}

// GetIp4publicOk returns a tuple with the Ip4public field value
// and a boolean to check if the value has been set.
func (o *VpcIdPutRequest) GetIp4publicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip4public, true
}

// SetIp4public sets field value
func (o *VpcIdPutRequest) SetIp4public(v string) {
	o.Ip4public = v
}

// GetIp4private returns the Ip4private field value if set, zero value otherwise.
func (o *VpcIdPutRequest) GetIp4private() string {
	if o == nil || IsNil(o.Ip4private) {
		var ret string
		return ret
	}
	return *o.Ip4private
}

// GetIp4privateOk returns a tuple with the Ip4private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcIdPutRequest) GetIp4privateOk() (*string, bool) {
	if o == nil || IsNil(o.Ip4private) {
		return nil, false
	}
	return o.Ip4private, true
}

// HasIp4private returns a boolean if a field has been set.
func (o *VpcIdPutRequest) HasIp4private() bool {
	if o != nil && !IsNil(o.Ip4private) {
		return true
	}

	return false
}

// SetIp4private gets a reference to the given string and assigns it to the Ip4private field.
func (o *VpcIdPutRequest) SetIp4private(v string) {
	o.Ip4private = &v
}

func (o VpcIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ip4public"] = o.Ip4public
	if !IsNil(o.Ip4private) {
		toSerialize["ip4private"] = o.Ip4private
	}
	return toSerialize, nil
}

func (o *VpcIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ip4public",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcIdPutRequest := _VpcIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVpcIdPutRequest)

	if err != nil {
		return err
	}

	*o = VpcIdPutRequest(varVpcIdPutRequest)

	return err
}

type NullableVpcIdPutRequest struct {
	value *VpcIdPutRequest
	isSet bool
}

func (v NullableVpcIdPutRequest) Get() *VpcIdPutRequest {
	return v.value
}

func (v *NullableVpcIdPutRequest) Set(val *VpcIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcIdPutRequest(val *VpcIdPutRequest) *NullableVpcIdPutRequest {
	return &NullableVpcIdPutRequest{value: val, isSet: true}
}

func (v NullableVpcIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


