/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterPostRequest{}

// ClusterPostRequest struct for ClusterPostRequest
type ClusterPostRequest struct {
	// Cluster name
	Name *string `json:"name,omitempty"`
	// Cluster location
	Location *string `json:"location,omitempty"`
	// Number of initial worker nodes
	Size *int32 `json:"size,omitempty"`
	// Networking plugin
	Cni *string `json:"cni,omitempty"`
}

// NewClusterPostRequest instantiates a new ClusterPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterPostRequest() *ClusterPostRequest {
	this := ClusterPostRequest{}
	return &this
}

// NewClusterPostRequestWithDefaults instantiates a new ClusterPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterPostRequestWithDefaults() *ClusterPostRequest {
	this := ClusterPostRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterPostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterPostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterPostRequest) SetName(v string) {
	o.Name = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ClusterPostRequest) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPostRequest) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ClusterPostRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ClusterPostRequest) SetLocation(v string) {
	o.Location = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ClusterPostRequest) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPostRequest) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ClusterPostRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ClusterPostRequest) SetSize(v int32) {
	o.Size = &v
}

// GetCni returns the Cni field value if set, zero value otherwise.
func (o *ClusterPostRequest) GetCni() string {
	if o == nil || IsNil(o.Cni) {
		var ret string
		return ret
	}
	return *o.Cni
}

// GetCniOk returns a tuple with the Cni field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPostRequest) GetCniOk() (*string, bool) {
	if o == nil || IsNil(o.Cni) {
		return nil, false
	}
	return o.Cni, true
}

// HasCni returns a boolean if a field has been set.
func (o *ClusterPostRequest) HasCni() bool {
	if o != nil && !IsNil(o.Cni) {
		return true
	}

	return false
}

// SetCni gets a reference to the given string and assigns it to the Cni field.
func (o *ClusterPostRequest) SetCni(v string) {
	o.Cni = &v
}

func (o ClusterPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Cni) {
		toSerialize["cni"] = o.Cni
	}
	return toSerialize, nil
}

type NullableClusterPostRequest struct {
	value *ClusterPostRequest
	isSet bool
}

func (v NullableClusterPostRequest) Get() *ClusterPostRequest {
	return v.value
}

func (v *NullableClusterPostRequest) Set(val *ClusterPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterPostRequest(val *ClusterPostRequest) *NullableClusterPostRequest {
	return &NullableClusterPostRequest{value: val, isSet: true}
}

func (v NullableClusterPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


