/*
Entrywan API

Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.

API version: v1beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterIdScalePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterIdScalePutRequest{}

// ClusterIdScalePutRequest struct for ClusterIdScalePutRequest
type ClusterIdScalePutRequest struct {
	// Number of worker nodes to scale the cluster to
	Size *int32 `json:"size,omitempty"`
}

// NewClusterIdScalePutRequest instantiates a new ClusterIdScalePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterIdScalePutRequest() *ClusterIdScalePutRequest {
	this := ClusterIdScalePutRequest{}
	return &this
}

// NewClusterIdScalePutRequestWithDefaults instantiates a new ClusterIdScalePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterIdScalePutRequestWithDefaults() *ClusterIdScalePutRequest {
	this := ClusterIdScalePutRequest{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ClusterIdScalePutRequest) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterIdScalePutRequest) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ClusterIdScalePutRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ClusterIdScalePutRequest) SetSize(v int32) {
	o.Size = &v
}

func (o ClusterIdScalePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterIdScalePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableClusterIdScalePutRequest struct {
	value *ClusterIdScalePutRequest
	isSet bool
}

func (v NullableClusterIdScalePutRequest) Get() *ClusterIdScalePutRequest {
	return v.value
}

func (v *NullableClusterIdScalePutRequest) Set(val *ClusterIdScalePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterIdScalePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterIdScalePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterIdScalePutRequest(val *ClusterIdScalePutRequest) *NullableClusterIdScalePutRequest {
	return &NullableClusterIdScalePutRequest{value: val, isSet: true}
}

func (v NullableClusterIdScalePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterIdScalePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


